/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Impl.DAOConfigEmpresaImpl;
import interfaces.DAOConfigEmpresa;
import java.awt.Color;
import javax.swing.JOptionPane;
import models.ConfigEmpresa;

/**
 *
 * @author User
 */
public class PanConfig extends javax.swing.JPanel {

    /**
     * Creates new form PanConfig
     */
    public PanConfig() {
        initComponents();
        cargarConfigEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtRazon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        introduccion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnActualizarDatosConfig = new javax.swing.JButton();

        txtRazon.setBackground(new java.awt.Color(153, 153, 153));
        txtRazon.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtRazon.setForeground(new java.awt.Color(255, 255, 255));
        txtRazon.setBorder(new javax.swing.border.MatteBorder(null));
        txtRazon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setText("Razon de Emision de factura");

        txtNit.setBackground(new java.awt.Color(153, 153, 153));
        txtNit.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNit.setForeground(new java.awt.Color(255, 255, 255));
        txtNit.setBorder(new javax.swing.border.MatteBorder(null));
        txtNit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setText("Nit");

        txtDireccion.setBackground(new java.awt.Color(153, 153, 153));
        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(new javax.swing.border.MatteBorder(null));
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Direccion");

        txtNombre.setBackground(new java.awt.Color(153, 153, 153));
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(new javax.swing.border.MatteBorder(null));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setText("Nombre Empresa");

        introduccion.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        introduccion.setText("Configuracion de los datos de la empresa en la factura");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnActualizarDatosConfig.setBackground(new java.awt.Color(153, 153, 153));
        btnActualizarDatosConfig.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnActualizarDatosConfig.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarDatosConfig.setText("ACTUALIZAR DATOS");
        btnActualizarDatosConfig.setBorderPainted(false);
        btnActualizarDatosConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarDatosConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarDatosConfigMouseExited(evt);
            }
        });
        btnActualizarDatosConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDatosConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(btnActualizarDatosConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(introduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(introduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(btnActualizarDatosConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarDatosConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarDatosConfigMouseEntered
        btnActualizarDatosConfig.setBackground(new Color(53, 53, 53));
        btnActualizarDatosConfig.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnActualizarDatosConfigMouseEntered

    private void btnActualizarDatosConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarDatosConfigMouseExited
        btnActualizarDatosConfig.setBackground(new Color(153, 153, 153));
        btnActualizarDatosConfig.setForeground(Color.black);
    }//GEN-LAST:event_btnActualizarDatosConfigMouseExited

    private void btnActualizarDatosConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDatosConfigActionPerformed
        ConfigEmpresa configEmpresa = new ConfigEmpresa();
        DAOConfigEmpresa dao = new DAOConfigEmpresaImpl();

        // Suponiendo que tienes cuatro JTextFields: txtNombreEmpresa, txtNIT, txtDireccion, txtRazon
        configEmpresa.setIdConfig(1); // Asegúrate de establecer el ID correcto que quieres actualizar
        configEmpresa.setNombreEmpresa(txtNombre.getText());
        configEmpresa.setNIT(txtNit.getText());
        configEmpresa.setDireccion(txtDireccion.getText());
        configEmpresa.setRazon(txtRazon.getText());

        try {
            if (dao.actualizarConfigEmpresa(configEmpresa)) {
                JOptionPane.showMessageDialog(null, "Configuración de empresa actualizada con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar la configuración de la empresa");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al actualizar la configuración de la empresa");
        }
    }//GEN-LAST:event_btnActualizarDatosConfigActionPerformed

    
    private void cargarConfigEmpresa() {
    DAOConfigEmpresa dao = new DAOConfigEmpresaImpl();

    try {
        ConfigEmpresa config = dao.obtenerConfigEmpresa(1); // Asumiendo que el idConfig es 1
        if (config != null) {
            txtNombre.setText(config.getNombreEmpresa());
            txtNit.setText(config.getNIT());
            txtDireccion.setText(config.getDireccion());
            txtRazon.setText(config.getRazon());
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró la configuración de la empresa");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar la configuración de la empresa");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnActualizarDatosConfig;
    private javax.swing.JLabel introduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRazon;
    // End of variables declaration//GEN-END:variables
}
