/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Color;

/**
 *
 * @author User
 */
public class PanInventario extends javax.swing.JPanel {

    /**
     * Creates new form PanPrincipal
     */
    public PanInventario() {
        initComponents();
        InitStyles();
    }
    
    private void InitStyles(){
        bienvenido.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        bienvenido.setForeground(Color.BLACK);
        introduccion.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        introduccion.setForeground(Color.BLACK);
        opciones.putClientProperty("FlatLaf.styleClass", "large");
        opciones.setForeground(Color.BLACK);
        opciones2.putClientProperty("FlatLaf.styleClass", "large");
        opciones2.setForeground(Color.BLACK);
        opciones3.putClientProperty("FlatLaf.styleClass", "large");
        opciones3.setForeground(Color.BLACK);
        opciones4.putClientProperty("FlatLaf.styleClass", "large");
        opciones4.setForeground(Color.BLACK);
        opciones5.putClientProperty("FlatLaf.styleClass", "large");
        opciones5.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        introduccion = new javax.swing.JLabel();
        opciones = new javax.swing.JLabel();
        opciones2 = new javax.swing.JLabel();
        opciones3 = new javax.swing.JLabel();
        opciones4 = new javax.swing.JLabel();
        opciones5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(225, 225, 225));
        setPreferredSize(new java.awt.Dimension(1020, 598));

        bg.setBackground(new java.awt.Color(225, 225, 225));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        bienvenido.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        bienvenido.setText("Inventario");

        introduccion.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        introduccion.setText("Sistema de gestion de Inovation Labs");

        opciones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        opciones.setText("- Control de Usuarios");

        opciones2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        opciones2.setText("- Administrar las ventas");

        opciones3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        opciones3.setText("- Informacion del cliente");

        opciones4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        opciones4.setText("- Informacion de proveedores");

        opciones5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        opciones5.setText("- Existencia en stock");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(653, 653, 653))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(introduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(506, 506, 506))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(678, 678, 678))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(opciones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(661, 661, 661))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(opciones3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(660, 660, 660))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(opciones4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(626, 626, 626))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(opciones5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(682, 682, 682))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(introduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(opciones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(opciones3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(opciones4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(opciones5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel introduccion;
    private javax.swing.JLabel opciones;
    private javax.swing.JLabel opciones2;
    private javax.swing.JLabel opciones3;
    private javax.swing.JLabel opciones4;
    private javax.swing.JLabel opciones5;
    // End of variables declaration//GEN-END:variables
}
